### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by ggukggukee** [nerdyman/react-compare-slider#103]
I'm using `react-compare-slider` on react 17.0.2 and got this error:

`ResizeObserver loop completed with undelivered notifications.`

**Comment by nerdyman** [comment]
Hi @ggukggukee, can you provide some reproduction steps? I've tried 17.0.2 in Codesandbox and it works ok. https://31y6cd.csb.app/

**Comment by ggukggukee** [comment]
I've noticed that I get this message in Safari. In Chrome there is no error.
(Safari 16.1 on MacOS Ventura 13.0)

**Comment by nerdyman** [comment]
@ggukggukee Thanks for the info! I can repro it on `17.0.2` but it's fine with React 18 on Safari so I'd upgrade if you can. Since it doesn't affect the functionality and only occurs on an older version of React with a specific browser I don't think it's worth fixing at the moment.

I've created another sandbox with the latest React version, let me know if you encounter any issues with it https://31y6cd.csb.app/
