### ISSUE TITLE
Add the ability to change aria-label of the component.

### ISSUE THREAD

**Issue by spiletski** [nerdyman/react-compare-slider#146]
There is no way to change aria-label of the component. It will be great to have a chance to change the value using a property. Especially helpful for translation and accessibility.

https://github.com/nerdyman/react-compare-slider/blob/main/lib/src/Container.tsx
```
 return (
    <button
      ref={ref}
      aria-label="Drag to move or focus and use arrow keys"
```

Thanks in advance!

**Comment by nerdyman** [comment]
@spiletski You can use `useReactCompareSliderRef` to access the internal components. It provides access to the DOM nodes so you can modify them however you like. To set the label you can do the following:

```tsx
const reactCompareSliderRef = useReactCompareSliderRef();

  useEffect(() => {
    reactCompareSliderRef.current.handleContainer?.setAttribute(
      'aria-label',
      'my custom label'
    );
  }, []);

  return (
    <ReactCompareSlider
      ref={reactCompareSliderRef}
      itemOne={
        <ReactCompareSliderImage
          alt="one"
          src="https://via.placeholder.com/600x400?text=one"
        />
      }
      itemTwo={
        <ReactCompareSliderImage
          alt="one"
          src="https://via.placeholder.com/600x400?text=two"
        />
      }
    />
  );
```

https://stackblitz.com/edit/vitejs-vite-lw748x?file=src%2FApp.tsx&terminal=dev

It would be nice if the `handle` component was the button instead of being wrapped in the button internally but I opted for wrapping to make the API easier to use. I'll revisit this when looking at the v4 release to see if there's an easy way to avoid the wrapping.

**Comment by nerdyman** [comment]
Awesome, thanks @spiletski.

I'll close this ticket and create a new feature one if I figure out a way to not wrap the button.
