### ISSUE TITLE
How to make draggable area to be on the handle only?

### ISSUE THREAD

**Issue by henrikra** [nerdyman/react-compare-slider#16]
First of all this is very good library but I have one UX problem in mind.

Specially when using with mobile if you have list of different `ReactCompareSlider`s which take full width of the mobile screen it is annoying to scroll list vertically because you accidentally start sliding the `ReactCompareSlider` even though you wanted to scroll content of the page vertically.

So would be nice to restrtict the area of `ReactCompareSlider` so that only if user drags the handle then it starts to drag `ReactCompareSlider`s content horizontally. What do you guys think?

**Comment by nerdyman** [comment]
@henrikra This has been added in `1.2.0`. The default handle doesn't work that well with this setting enabled because of its width. I'll be publishing v2 of this library in the coming weeks to fix this along with a few other features. In the meantime, you could use your own [custom handle](https://react-compare-slider-fbuvzk7ay.vercel.app/?path=/story/demos-handles--blurred-arrows).

The library doesn't automatically detect touch devices but I've added docs on [how to detect touch devices](https://react-compare-slider-fbuvzk7ay.vercel.app/?path=/story/docs-only-handle-draggable--page#detecting-touch-devices) if you haven't already got something configured.

Thanks for opening the issue, if it's not working as you expected (with the caveat above for the default handle) feel free to reopen the issue.

**Comment by henrikra** [comment]
@nerdyman Thx! Now I have tested the new version and it works like a charm!
